apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloworld-backend-pvc
  namespace: backend
spec:
  accessModes:
   - ReadWriteMany
  storageClassName: ""
  volumeName: helloworld-backend-pv 
  resources:
    requests:
      storage: 5Gi
