apiVersion: v1
kind: PersistentVolume
metadata:
 name: helloworld-backend-pv
 namespace: backend
spec:
 capacity:
   storage: 25Gi
 accessModes:
 - ReadWriteMany
 nfs:
   path: /filestore_vol1/helloworld/helloworld-backend-logs/
   server: 76.x.x.x
